server/web/blueprints/D4_sensors.py
#!/usr/bin/env python3
# -*-coding:UTF-8 -*

'''
    Flask functions and routes for all D4 sensors
'''

import os
import re
import sys
import json
import redis

sys.path.append(os.path.join(os.environ['D4_HOME'], 'lib'))
import ConfigLoader
import Sensor

from flask import Flask, render_template, jsonify, request, Blueprint, redirect, url_for, Response
from flask_login import login_required, current_user

from Role_Manager import login_admin, login_user_basic

# ============ BLUEPRINT ============

D4_sensors = Blueprint('D4_sensors', __name__, template_folder='templates')

# ============ VARIABLES ============

### Config ###
config_loader = ConfigLoader.ConfigLoader()
r_serv_metadata = config_loader.get_redis_conn("Redis_METADATA")
r_serv_db = config_loader.get_redis_conn("Redis_SERV")
config_loader = None
###  ###

# ============ FUNCTIONS ============


# ============= ROUTES ==============

@D4_sensors.route("/sensors/monitoring/add", methods=['GET'])
@login_required
@login_user_basic
def add_sensor_to_monitor():
    sensor_uuid = request.args.get("uuid")
    return render_template("sensors/add_sensor_to_monitor.html",
                                sensor_uuid=sensor_uuid)

@D4_sensors.route("/sensors/monitoring/add_post", methods=['POST'])
@login_required
@login_user_basic
def add_sensor_to_monitor_post():
    sensor_uuid = request.form.get("uuid")
    delta_time = request.form.get("delta_time")
    res = Sensor.api_add_sensor_to_monitor({'uuid':sensor_uuid, 'delta_time': delta_time})
    if res:
        Response(json.dumps(res[0], indent=2, sort_keys=True), mimetype='application/json'), res[1]
    return redirect(url_for('uuid_management', uuid=sensor_uuid))

@D4_sensors.route("/sensors/monitoring/delete", methods=['GET'])
@login_required
@login_user_basic
def delete_sensor_to_monitor():
    sensor_uuid = request.args.get("uuid")
    res = Sensor.api_delete_sensor_to_monitor({'uuid':sensor_uuid})
    if res:
        Response(json.dumps(res[0], indent=2, sort_keys=True), mimetype='application/json'), res[1]
    return redirect(url_for('uuid_management', uuid=sensor_uuid))


@D4_sensors.route("/sensors/monitoring/errors", methods=['GET'])
@login_required
@login_user_basic
def get_all_sensors_connection_errors():
    res = Sensor.api_get_all_sensors_connection_errors()
    return Response(json.dumps(res[0], indent=2, sort_keys=True), mimetype='application/json'), res[1]

server/web/templates/sensors/add_sensor_to_monitor.html
<!DOCTYPE html>

<html>
<head>
	<title>D4-Project</title>
	<link rel="icon" href="{{ url_for('static', filename='img/d4-logo.png')}}">
	<!-- Core CSS -->
	<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='font-awesome/css/font-awesome.css') }}" rel="stylesheet">

	<!-- JS -->
	<script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
	<script src="{{ url_for('static', filename='js/popper.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
</head>

<body>

	{% include 'navbar.html' %}

	<form action="{{ url_for('D4_sensors.add_sensor_to_monitor_post') }}" method="post" enctype=multipart/form-data>

		<div class="d-flex justify-content-center">
			<div class="col-sm-6">
				<h4 class="my-3">Monitor a Sensor</h4>
				<div class="form-group">
					<input class="form-control text-center bg-dark text-white" type="text" value="{{sensor_uuid}}" disabled>
					<input type="text" name="uuid" id="uuid" value="{{sensor_uuid}}" hidden>
				</div>

				<div class="input-group mt-2 mb-2">
					<div class="input-group-prepend">
						<span class="input-group-text bg-light"><i class="fa fa-clock-o"></i>&nbsp;</span>
					</div>
					<input class="form-control" type="number" id="delta_time" value="3600" min="30" name="delta_time" required>
					<div class="input-group-append">
						<span class="input-group-text">Maxinum Time (seconds) between two D4 packets</span>
					</div>
				</div>

				<div class="form-group">
					<button class="btn btn-primary" type="submit">Monitor Sensor</button>
				</div>
			</div>
		</div>

	</form>

	{% include 'navfooter.html' %}
</body>

<script>
$(document).ready(function(){
	$("#nav-sensor").addClass("active");
});

</script>