server/web/blueprints/analyzer_queue.py
#!/usr/bin/env python3
# -*-coding:UTF-8 -*

'''
    Flask functions and routes for the rest api
'''

import os
import re
import sys
import redis

sys.path.append(os.path.join(os.environ['D4_HOME'], 'lib'))
import ConfigLoader
import Analyzer_Queue

from flask import Flask, render_template, jsonify, request, Blueprint, redirect, url_for, Response
from flask_login import login_required, current_user

from Role_Manager import login_admin, login_user_basic

# ============ BLUEPRINT ============

analyzer_queue = Blueprint('analyzer_queue', __name__, template_folder='templates')

# ============ VARIABLES ============

### Config ###
config_loader = ConfigLoader.ConfigLoader()
r_serv_metadata = config_loader.get_redis_conn("Redis_METADATA")
r_serv_db = config_loader.get_redis_conn("Redis_SERV")
config_loader = None
###  ###

# ============ FUNCTIONS ============


# ============= ROUTES ==============

@analyzer_queue.route("/analyzer_queue/create_queue", methods=['GET'])
@login_required
@login_user_basic
def create_analyzer_queue():
    return render_template("analyzer_queue/queue_creator.html")

@analyzer_queue.route("/analyzer_queue/create_queue_post", methods=['POST'])
@login_required
@login_user_basic
def create_analyzer_queue_post():
    l_queue_meta = ['analyzer_type', 'analyzer_metatype', 'description', 'analyzer_uuid']
    queue_type = request.form.get("analyzer_type")
    queue_metatype = request.form.get("analyzer_metatype")
    queue_description = request.form.get("description")
    queue_uuid = request.form.get("analyzer_uuid")

    queue_type = Analyzer_Queue.sanitize_queue_type(queue_type)

    # unpack uuid group
    l_uuid = set()
    l_invalid_uuid = set()
    for obj_tuple in list(request.form):
        if obj_tuple not in l_queue_meta:
            sensor_uuid = request.form.get(obj_tuple)
            if Analyzer_Queue.is_valid_uuid_v4(sensor_uuid):
                l_uuid.add(sensor_uuid)
            else:
                if sensor_uuid:
                    l_invalid_uuid.add(sensor_uuid)

    l_uuid = list(l_uuid)
    l_invalid_uuid = list(l_invalid_uuid)
    if l_invalid_uuid:
        return render_template("analyzer_queue/queue_creator.html", queue_uuid=queue_uuid, queue_type=queue_type, metatype_name=queue_metatype,
                                    description=queue_description, l_uuid=l_uuid, l_invalid_uuid=l_invalid_uuid)

    res = Analyzer_Queue.create_queues(queue_type, queue_uuid=queue_uuid, l_uuid=l_uuid, metatype_name=queue_metatype, description=queue_description)
    if isinstance(res,dict):
        return jsonify(res)
    if res:
        return redirect(url_for('server_management', _anchor=res))

@analyzer_queue.route("/analyzer_queue/edit_queue", methods=['GET'])
@login_required
@login_user_basic
def edit_queue_analyzer_queue():
    queue_uuid = request.args.get("queue_uuid")
    queue_metadata = Analyzer_Queue.get_queue_metadata(queue_uuid, is_group=True)
    if 'is_group_queue' in queue_metadata:
        l_sensors_uuid = Analyzer_Queue.get_queue_group_all_sensors(queue_uuid)
    else:
        l_sensors_uuid = None
    return render_template("analyzer_queue/queue_editor.html", queue_metadata=queue_metadata, l_sensors_uuid=l_sensors_uuid)

@analyzer_queue.route("/analyzer_queue/edit_queue_post", methods=['POST'])
@login_required
@login_user_basic
def edit_queue_analyzer_queue_post():
    l_queue_meta = ['queue_uuid', 'description']
    queue_uuid = request.form.get("queue_uuid")
    queue_description = request.form.get("description")

    l_uuid = set()
    l_invalid_uuid = set()
    for obj_tuple in list(request.form):
        if obj_tuple not in l_queue_meta:
            sensor_uuid = request.form.get(obj_tuple)
            if Analyzer_Queue.is_valid_uuid_v4(sensor_uuid):
                l_uuid.add(sensor_uuid)
            else:
                if sensor_uuid:
                    l_invalid_uuid.add(sensor_uuid)

    if l_invalid_uuid:
        queue_metadata = Analyzer_Queue.get_queue_metadata(queue_uuid, is_group=True)
        if queue_description:
            queue_metadata['description'] = queue_description
        return render_template("analyzer_queue/queue_editor.html", queue_metadata=queue_metadata, l_sensors_uuid=l_uuid, l_invalid_uuid=l_invalid_uuid)

    Analyzer_Queue.edit_queue_description(queue_uuid, queue_description)
    Analyzer_Queue.edit_queue_sensors_set(queue_uuid, l_uuid)

    return redirect(url_for('analyzer_queue.edit_queue_analyzer_queue', queue_uuid=queue_uuid))

server/web/templates/analyzer_queue/block_add_sensor_to_group_block.html
<div class="input-group mb-1">
  <input type="text" class="form-control col-10 {%if error%}is-invalid{%else%}is-valid{%endif%}" name="{{sensor_uuid}}" value="{{sensor_uuid}}">
  <span class="btn btn-danger input-group-addon delete-field col-2"><i class="fa fa-trash"></i></span>
  <div class="invalid-feedback">
    Please provide a valid UUID v4.
  </div>
</div>

server/web/templates/analyzer_queue/queue_creator.html
<!DOCTYPE html>

<html>
<head>
	<title>D4-Project</title>
	<link rel="icon" href="{{ url_for('static', filename='img/d4-logo.png')}}">
	<!-- Core CSS -->
	<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='font-awesome/css/font-awesome.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/dataTables.bootstrap.min.css') }}" rel="stylesheet">

	<!-- JS -->
	<script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
	<script src="{{ url_for('static', filename='js/popper.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/jquery.dataTables.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/dataTables.bootstrap.min.js')}}"></script>

  <style>
	.popover{
		max-width: 100%;
	}
  </style>


</head>

<body>

	{% include 'navbar.html' %}



		<div class="card mb-3 mt-1">
			<div class="card-header text-white bg-dark">
				<h5 class="card-title">Create Analyzer Queue</h5>
			</div>
			<div class="card-body">

				<form action="{{ url_for('analyzer_queue.create_analyzer_queue_post') }}" method="post" enctype=multipart/form-data onsubmit="submitPaste()">

					<div class="form-group mb-4">
						<label for="analyzer_type"><b>Analyzer Type</b></label>
						<input class="form-control col-md-4" type="number" name="analyzer_type" id="analyzer_type" value="{%if queue_type%}{{queue_type}}{%else%}1{%endif%}" min="1" max="254" required>
						<input class="form-control" type="text" name="analyzer_metatype" id="analyzer_metatype_name" placeholder="Meta Type Name" {%if metatype_name%}value="{{metatype_name}}"{%endif%}>
					</div>

					<div class="input-group my-2">
						<div class="input-group-prepend">
							<button class="btn btn-outline-secondary" type="button" onclick="generate_new_uuid();"><i class="fa fa-random"></i></button>
						</div>
						<input class="form-control col-md-4" type="text" name="analyzer_uuid" id="analyzer_uuid" {%if queue_uuid%}value="{{queue_uuid}}"{%endif%} required placeholder="Analyzer uuid - (Optional)">
					</div>

					<div class="form-group my-2">
						<input class="form-control" type="text" name="description" id="analyzer_description" {%if description%}value="{{description}}"{%endif%} required placeholder="Description - (Optional)">
					</div>

					<div id="container-id-to-import">

						<p>Create Queue by Group of UUID</p>

						<div for="first_sensor_uuid"><b>Sensor UUID</b></div>

						<div class="form-horizontal">
							<div class="form-body">
								<div class="form-group">
									<div class="fields">

										{% if l_uuid %}
											{% for sensor_uuid in l_uuid %}
											  {% with sensor_uuid=sensor_uuid, error=False%}
											    {% include 'analyzer_queue/block_add_sensor_to_group_block.html' %}
											  {% endwith %}
											{% endfor %}
											<br>
										{% endif %}
										{% if l_invalid_uuid %}
											{% for sensor_uuid in l_invalid_uuid %}
											  {% with sensor_uuid=sensor_uuid, error=True%}
											    {% include 'analyzer_queue/block_add_sensor_to_group_block.html' %}
											  {% endwith %}
											{% endfor %}
											<br>
										{% endif %}
										<div class="input-group mb-1">
											<input type="text" class="form-control col-10" name="first_sensor_uuid" id="first_sensor_uuid">
										  <span class="btn btn-info input-group-addon add-field col-2"><i class="fa fa-plus"></i></span>
										</div>
										<span class="help-block" hidden>Export Objects</span>
									</div>
								</div>
							</div>
						</div>

					</div>

					<div class="form-group">
						<button class="btn btn-info" type="submit">Create Queue</button>
					</div>

				</form>

			</div>
		</div>


	{% include 'navfooter.html' %}
</body>

<script>
$(document).ready(function(){
	$("#nav-sensor").addClass("active");
	{%if queue_type!=2 and queue_type!=254%}
		$('#analyzer_metatype_name').hide();
	{%endif%}
});


var input_part_1 = '<div class="input-group mb-1"><input type="text" class="form-control col-10" name="'
var input_part_2 = '"></div>'
var minusButton = '<span class="btn btn-danger input-group-addon delete-field col-2"><i class="fa fa-trash"></i></span>'

$('.add-field').click(function() {
	var new_uuid = uuidv4();
	var template = input_part_1 + new_uuid + input_part_2;
  var temp = $(template).insertBefore('.help-block');
  temp.append(minusButton);
});

$('.fields').on('click', '.delete-field', function(){
	console.log($(this).parent());
  $(this).parent().remove();
	//$.get( "#")
});

function uuidv4() {
  return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, c =>
    (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
  );
}

$('#analyzer_type').on('input', function() {
	if ($('#analyzer_type').val() == 2 || $('#analyzer_type').val() == 254){
		$('#analyzer_metatype_name').show()
	} else {
		$('#analyzer_metatype_name').hide()
	}
});

function generate_new_uuid(){
	$.getJSON( "{{url_for('generate_uuid')}}", function( data ) {
		console.log(data['uuid'])
		$( "#analyzer_uuid" ).val(data['uuid']);
	});
}

</script>

server/web/templates/analyzer_queue/queue_editor.html
<!DOCTYPE html>

<html>
<head>
	<title>D4-Project</title>
	<link rel="icon" href="{{ url_for('static', filename='img/d4-logo.png')}}">
	<!-- Core CSS -->
	<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='font-awesome/css/font-awesome.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/dataTables.bootstrap.min.css') }}" rel="stylesheet">

	<!-- JS -->
	<script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
	<script src="{{ url_for('static', filename='js/popper.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/jquery.dataTables.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/dataTables.bootstrap.min.js')}}"></script>

  <style>
	.popover{
		max-width: 100%;
	}
  </style>


</head>

<body>

	{% include 'navbar.html' %}



		<div class="card mb-3 mt-1">
			<div class="card-header text-white bg-dark">
				<h5 class="card-title">Analyzer Queue: <b>{{queue_metadata['uuid']}}</b></h5>
			</div>
			<div class="card-body">

							<table class="table table-striped table-bordered">
								<thead class="thead-dark">
									<tr>
										<th>Type Name</th>
										<th>Group</th>
										<th style="max-width: 800px;">Name</th>
										<th style="max-width: 800px;">Last updated</th>
										<th style="max-width: 800px;">Change max size limit</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>
											{%if queue_metadata['format_type'] == 254%}
												{{queue_metadata['extended_type']}}
											{%else%}
												{{queue_metadata['format_type']}}
											{%endif%}
										</td>
											{%if queue_metadata['is_group_queue']%}
												<td class="text-center"><i class="fa fa-group"></i></td>
											{%else%}
												<td></td>
											{%endif%}
										<td>
											<div class="d-flex">
												<b>{{queue_metadata['uuid']}}:{{queue_metadata['format_type']}}{%if queue_metadata['format_type'] == 254%}:{{queue_metadata['extended_type']}}{%endif%}</b>
											</div>
										</td>
										<td>{{queue_metadata['last_updated']}}</td>
										<td>
											<div class="d-xl-flex justify-content-xl-center">
												<input class="form-control mr-lg-1" style="max-width: 100px;" type="number" id="max_size_analyzer_{{queue_metadata['uuid']}}" value="{{queue_metadata['size_limit']}}" min="0" required="">
												<button type="button" class="btn btn-outline-secondary" onclick="window.location.href ='{{ url_for('analyzer_change_max_size') }}?analyzer_uuid={{queue_metadata['uuid']}}&redirect=0&max_size_analyzer='+$('#max_size_analyzer_{{queue_metadata['uuid']}}').val();">Change Max Size</button>
											</div>
										</td>
									</tr>
								</tbody>
							</table>

				<form action="{{ url_for('analyzer_queue.edit_queue_analyzer_queue_post') }}" method="post" enctype=multipart/form-data>

					<input class="form-control" type="text" name="queue_uuid" id="queue_uuid" value="{{queue_metadata['uuid']}}" hidden>

					<div class="form-group my-2">
						<input class="form-control" type="text" name="description" id="analyzer_description" {%if 'description' in queue_metadata%}value="{{queue_metadata['description']}}"{%endif%} placeholder="Description - (Optional)">
					</div>

					<div>

						<br>

						<div for="first_sensor_uuid"><b>Sensor UUID</b></div>

						<div class="form-horizontal">
							<div class="form-body">
								<div class="form-group">
									<div class="fields">

										{% if l_sensors_uuid %}
											{% for sensor_uuid in l_sensors_uuid %}
											  {% with sensor_uuid=sensor_uuid, error=False%}
											    {% include 'analyzer_queue/block_add_sensor_to_group_block.html' %}
											  {% endwith %}
											{% endfor %}
											<br>
										{% endif %}
										{% if l_invalid_uuid %}
											{% for sensor_uuid in l_invalid_uuid %}
											  {% with sensor_uuid=sensor_uuid, error=True%}
											    {% include 'analyzer_queue/block_add_sensor_to_group_block.html' %}
											  {% endwith %}
											{% endfor %}
											<br>
										{% endif %}
										<div class="input-group mb-1">
											<input type="text" class="form-control col-10" name="first_sensor_uuid" id="first_sensor_uuid">
										  <span class="btn btn-info input-group-addon add-field col-2"><i class="fa fa-plus"></i></span>
										</div>
										<span class="help-block" hidden>Sensor UUID</span>
									</div>
								</div>
							</div>
						</div>

					</div>

					<div class="form-group">
						<button class="btn btn-info" type="submit">Edit Queue</button>
					</div>

				</form>

			</div>
		</div>


	{% include 'navfooter.html' %}
</body>

<script>
$(document).ready(function(){
});


var input_part_1 = '<div class="input-group mb-1"><input type="text" class="form-control col-10" name="'
var input_part_2 = '"></div>'
var minusButton = '<span class="btn btn-danger input-group-addon delete-field col-2"><i class="fa fa-trash"></i></span>'

$('.add-field').click(function() {
	var new_uuid = uuidv4();
	var template = input_part_1 + new_uuid + input_part_2;
  var temp = $(template).insertBefore('.help-block');
  temp.append(minusButton);
});

$('.fields').on('click', '.delete-field', function(){
	console.log($(this).parent());
  $(this).parent().remove();
	//$.get( "#")
});

function uuidv4() {
  return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, c =>
    (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
  );
}

</script>