server/web/blueprints/settings.py
#!/usr/bin/env python3
# -*-coding:UTF-8 -*

'''
    Flask functions and routes for the rest api
'''

import os
import re
import sys
import redis

sys.path.append(os.path.join(os.environ['D4_HOME'], 'lib'))
import ConfigLoader

from flask import Flask, render_template, jsonify, request, Blueprint, redirect, url_for, Response
from flask_login import login_required, current_user

from Role_Manager import login_admin, login_user_basic
from Role_Manager import create_user_db, edit_user_db, delete_user_db, check_password_strength, generate_new_token, gen_password, get_all_role

# ============ BLUEPRINT ============

settings = Blueprint('settings', __name__, template_folder='templates')

# ============ VARIABLES ============

email_regex = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}'
email_regex = re.compile(email_regex)

### Config ###
config_loader = ConfigLoader.ConfigLoader()
r_serv_metadata = config_loader.get_redis_conn("Redis_METADATA")
r_serv_db = config_loader.get_redis_conn("Redis_SERV")
config_loader = None
###  ###

# ============ FUNCTIONS ============

def one():
    return 1

def check_email(email):
    return email_regex.match(email)

def get_user_metadata(user_id):
    user_metadata = {}
    user_metadata['email'] = user_id
    user_metadata['role'] = r_serv_db.hget('user_metadata:{}'.format(user_id), 'role')
    user_metadata['api_key'] = r_serv_db.hget('user_metadata:{}'.format(user_id), 'token')
    return user_metadata

def get_users_metadata(list_users):
    users = []
    for user in list_users:
        users.append(get_user_metadata(user))
    return users

def get_all_users():
    return r_serv_db.hkeys('user:all')


# ============= ROUTES ==============

@settings.route("/settings/", methods=['GET'])
@login_required
@login_user_basic
def settings_page():
    return redirect(url_for('settings.edit_profile'))

@settings.route("/settings/edit_profile", methods=['GET'])
@login_required
@login_user_basic
def edit_profile():
    user_metadata = get_user_metadata(current_user.get_id())
    admin_level = current_user.is_in_role('admin')
    return render_template("edit_profile.html", user_metadata=user_metadata,
                            admin_level=admin_level)

@settings.route("/settings/new_token", methods=['GET'])
@login_required
@login_user_basic
def new_token():
    generate_new_token(current_user.get_id())
    return redirect(url_for('settings.edit_profile'))

@settings.route("/settings/new_token_user", methods=['GET'])
@login_required
@login_admin
def new_token_user():
    user_id = request.args.get('user_id')
    if r_serv_db.exists('user_metadata:{}'.format(user_id)):
        generate_new_token(user_id)
    return redirect(url_for('settings.users_list'))

@settings.route("/settings/create_user", methods=['GET'])
@login_required
@login_admin
def create_user():
    user_id = request.args.get('user_id')
    error = request.args.get('error')
    error_mail = request.args.get('error_mail')
    role = None
    if r_serv_db.exists('user_metadata:{}'.format(user_id)):
        role = r_serv_db.hget('user_metadata:{}'.format(user_id), 'role')
    else:
        user_id = None
    all_roles = get_all_role()
    return render_template("create_user.html", all_roles=all_roles, user_id=user_id, user_role=role,
                                        error=error, error_mail=error_mail,
                                        admin_level=True)

@settings.route("/settings/create_user_post", methods=['POST'])
@login_required
@login_admin
def create_user_post():
    email = request.form.get('username')
    role = request.form.get('user_role')
    password1 = request.form.get('password1')
    password2 = request.form.get('password2')

    all_roles = get_all_role()

    if email and len(email)< 300 and check_email(email) and role:
        if role in all_roles:
            # password set
            if password1 and password2:
                if password1==password2:
                    if check_password_strength(password1):
                        password = password1
                    else:
                        return render_template("create_user.html", all_roles=all_roles, error="Incorrect Password", admin_level=True)
                else:
                    return render_template("create_user.html", all_roles=all_roles, error="Passwords don't match", admin_level=True)
            # generate password
            else:
                password = gen_password()

            if current_user.is_in_role('admin'):
                # edit user
                if r_serv_db.exists('user_metadata:{}'.format(email)):
                    if password1 and password2:
                        edit_user_db(email, password=password, role=role)
                        return redirect(url_for('settings.users_list', new_user=email, new_user_password=password, new_user_edited=True))
                    else:
                        edit_user_db(email, role=role)
                        return redirect(url_for('settings.users_list', new_user=email, new_user_password='Password not changed', new_user_edited=True))
                # create user
                else:
                    create_user_db(email, password, default=True, role=role)
                    return redirect(url_for('settings.users_list', new_user=email, new_user_password=password, new_user_edited=False))

        else:
            return render_template("create_user.html", all_roles=all_roles, admin_level=True)
    else:
        return render_template("create_user.html", all_roles=all_roles, error_mail=True, admin_level=True)

@settings.route("/settings/users_list", methods=['GET'])
@login_required
@login_admin
def users_list():
    all_users = get_users_metadata(get_all_users())
    new_user = request.args.get('new_user')
    new_user_dict = {}
    if new_user:
        new_user_dict['email'] = new_user
        new_user_dict['edited'] = request.args.get('new_user_edited')
        new_user_dict['password'] = request.args.get('new_user_password')
    return render_template("users_list.html", all_users=all_users, new_user=new_user_dict, admin_level=True)

@settings.route("/settings/edit_user", methods=['GET'])
@login_required
@login_admin
def edit_user():
    user_id = request.args.get('user_id')
    return redirect(url_for('settings.create_user', user_id=user_id))

@settings.route("/settings/delete_user", methods=['GET'])
@login_required
@login_admin
def delete_user():
    user_id = request.args.get('user_id')
    delete_user_db(user_id)
    return redirect(url_for('settings.users_list'))

server/web/templates/blacklisted_ip.html
<!DOCTYPE html>

<html>
<head>
	<title>D4-Project</title>
	<link rel="icon" href="{{ url_for('static', filename='img/d4-logo.png')}}">
	<!-- Core CSS -->
	<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='font-awesome/css/font-awesome.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/dataTables.bootstrap.min.css') }}" rel="stylesheet">

	<!-- JS -->
	<script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
	<script src="{{ url_for('static', filename='js/jquery.dataTables.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/dataTables.bootstrap.min.js')}}"></script>

  <style>

  </style>


</head>

<body>

	{% include 'navbar.html' %}

	<div class="card-deck justify-content-center ml-0 mr-0">
		<div class="card border-dark mt-3 ml-4 mr-4">
			<div class="card-header bg-dark text-white">
				Blacklisted IP
			</div>
		  <div class="card-body text-dark">

				<div class="row">
			    <div class="col-sm-5">
						<table class="table table-striped table-bordered table-hover" id="myTable_1">
							<thead class="thead-dark">
								<tr>
									<th style="max-width: 800px;">IP</th>
									<th style="max-width: 800px;">Unblacklist IP</th>
								</tr>
							</thead>
							<tbody>
								{% for ip in list_blacklisted_ip_1 %}
								<tr>
									<td>{{ip}}</td>
									<td>
										<a href="{{ url_for('unblacklist_ip') }}?page={{page}}&ip={{ip}}">
											<button type="button" class="btn btn-outline-danger">UnBlacklist IP</button>
										</a>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
			    <div class="col-sm-2">
						<div class="card text-center border-danger" style="max-width: 20rem;">
						  <div class="card-body text-danger">
						    <h5 class="card-title">Blacklist IP</h5>
									<input type="text" class="form-control {%if blacklisted_ip is not none %}{%if blacklisted_ip==1 %}is-valid{% else %}is-invalid{%endif%}{%endif%}" id="blacklist_ip_input" placeholder="IP Address">
									<div class="invalid-feedback">
										{%if blacklisted_ip==2 %}
											This IP is already blacklisted
										{% else %}
											Incorrect IP address
										{% endif %}
					        </div>
									<div class="valid-feedback">
					          IP Blacklisted
					        </div>
							    <button type="button" class="btn btn-danger mt-2" onclick="window.location.href ='{{ url_for('blacklist_ip') }}?redirect=0&ip='+$('#blacklist_ip_input').val();">Blacklist IP</button>
						  </div>
						</div>
						<div class="card text-center border-success mt-4" style="max-width: 20rem;">
							<div class="card-body">
								<h5 class="card-title">Unblacklist IP</h5>
									<input type="text" class="form-control {%if unblacklisted_ip is not none %}{%if unblacklisted_ip==1 %}is-valid{% else %}is-invalid{%endif%}{%endif%}" id="unblacklist_ip_input" placeholder="IP Address">
									<div class="invalid-feedback">
										{%if unblacklisted_ip==2 %}
											This IP is not blacklisted
										{% else %}
											Incorrect IP address
										{% endif %}
									</div>
									<div class="valid-feedback">
										IP Unblacklisted
									</div>
									<button type="button" class="btn btn-outline-secondary mt-2" onclick="window.location.href ='{{ url_for('unblacklist_ip') }}?redirect=0&ip='+$('#unblacklist_ip_input').val();">Unblacklist IP</button>
							</div>
						</div>
					</div>
					<div class="col-sm-5">
						<table class="table table-striped table-bordered table-hover" id="myTable_2">
							<thead class="thead-dark">
								<tr>
									<th style="max-width: 800px;">IP</th>
									<th style="max-width: 800px;">Unblacklist IP</th>
								</tr>
							</thead>
							<tbody>
								{% for ip in list_blacklisted_ip_2 %}
								<tr>
									<td>{{ip}}</td>
									<td>
										<a href="{{ url_for('unblacklist_ip') }}?page={{page}}&ip={{ip}}">
											<button type="button" class="btn btn-outline-danger">UnBlacklist IP</button>
										</a>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
			  </div>
			</div>
		</div>

	</div>

	<div class="d-flex justify-content-center">
		<nav class="mt-4" aria-label="...">
			<ul class="pagination">
				<li class="page-item {%if page==1%}disabled{%endif%}">
					<a class="page-link" href="{{ url_for('blacklisted_ip') }}?page={{page-1}}">Previous</a>
				</li>

				{%if page>3%}
					<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_ip') }}?page=1">1</a></li>
					<li class="page-item disabled"><a class="page-link" aria-disabled="true" href="#">...</a></li>
					<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_ip') }}?page={{page-1}}">{{page-1}}</a></li>
					<li class="page-item active"><a class="page-link" href="{{ url_for('blacklisted_ip') }}?page={{page}}">{{page}}</a></li>
				{%else%}
				{%if page>2%}<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_ip') }}?page={{page-2}}">{{page-2}}</a></li>{%endif%}
				{%if page>1%}<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_ip') }}?page={{page-1}}">{{page-1}}</a></li>{%endif%}
				<li class="page-item active"><a class="page-link" href="{{ url_for('blacklisted_ip') }}?page={{page}}">{{page}}</a></li>
				{%endif%}

				{%if nb_page_max-page>3%}
					<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_ip') }}?page={{page+1}}">{{page+1}}</a></li>
					<li class="page-item disabled"><a class="page-link" aria-disabled="true" href="#">...</a></li>
					<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_ip') }}?page={{nb_page_max}}">{{nb_page_max}}</a></li>
				{%else%}
					{%if nb_page_max-page>2%}<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_ip') }}?page={{nb_page_max-2}}">{{nb_page_max-2}}</a></li>{%endif%}
					{%if nb_page_max-page>1%}<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_ip') }}?page={{nb_page_max-1}}">{{nb_page_max-1}}</a></li>{%endif%}
					{%if nb_page_max-page>0%}<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_ip') }}?page={{nb_page_max}}">{{nb_page_max}}</a></li>{%endif%}
				{%endif%}



				<li class="page-item {%if page==nb_page_max%}disabled{%endif%}">
					<a class="page-link" href="{{ url_for('blacklisted_ip') }}?page={{page+1}}" aria-disabled="true">Next</a>
				</li>
			</ul>
		</nav>
		</div>

	{% include 'navfooter.html' %}
</body>

<script>
var table
$(document).ready(function(){

		table = $('#myTable_1').DataTable(
			{
				/*"aLengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
				"iDisplayLength": 10,*/
				"order": [[ 0, "asc" ]]
			}
		);

		table = $('#myTable_2').DataTable(
			{
				/*"aLengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
				"iDisplayLength": 10,*/
				"order": [[ 0, "asc" ]]
			}
		);

});
</script>

server/web/templates/blacklisted_uuid.html
<!DOCTYPE html>

<html>
<head>
	<title>D4-Project</title>
	<link rel="icon" href="{{ url_for('static', filename='img/d4-logo.png')}}">
	<!-- Core CSS -->
	<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='font-awesome/css/font-awesome.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/dataTables.bootstrap.min.css') }}" rel="stylesheet">

	<!-- JS -->
	<script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
	<script src="{{ url_for('static', filename='js/jquery.dataTables.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/dataTables.bootstrap.min.js')}}"></script>

  <style>

  </style>


</head>

<body>

	{% include 'navbar.html' %}

	<div class="card-deck justify-content-center ml-0 mr-0">
		<div class="card border-dark mt-3 ml-4 mr-4">
			<div class="card-header bg-dark text-white">
				Blacklisted UUID
			</div>
		  <div class="card-body text-dark">

				<div class="row">
			    <div class="col-sm-5">
						<table class="table table-striped table-bordered table-hover" id="myTable_1">
							<thead class="thead-dark">
								<tr>
									<th style="max-width: 800px;">UUID</th>
									<th style="max-width: 800px;">Unblacklist UUID</th>
								</tr>
							</thead>
							<tbody>
								{% for uuid in list_blacklisted_uuid_1 %}
								<tr>
									<td>{{uuid}}</td>
									<td>
										<a href="{{ url_for('unblacklist_uuid') }}?page={{page}}&uuid={{uuid}}">
											<button type="button" class="btn btn-outline-danger">UnBlacklist UUID</button>
										</a>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
			    <div class="col-sm-2">
						<div class="card text-center border-danger" style="max-width: 20rem;">
						  <div class="card-body text-danger">
						    <h5 class="card-title">Blacklist UUID</h5>
									<input type="text" class="form-control {%if blacklisted_uuid is not none %}{%if blacklisted_uuid==1 %}is-valid{% else %}is-invalid{%endif%}{%endif%}" id="blacklist_uuid_input" placeholder="UUID Address">
									<div class="invalid-feedback">
										{%if blacklisted_uuid==2 %}
											This UUID is already blacklisted
										{% else %}
											Incorrect UUID
										{% endif %}
					        </div>
									<div class="valid-feedback">
					          UUID Blacklisted
					        </div>
							    <button type="button" class="btn btn-danger mt-2" onclick="window.location.href ='{{ url_for('blacklist_uuid') }}?redirect=0&uuid='+$('#blacklist_uuid_input').val();">Blacklist UUID</button>
						  </div>
						</div>
						<div class="card text-center border-success mt-4" style="max-width: 20rem;">
							<div class="card-body">
								<h5 class="card-title">Unblacklist UUID</h5>
									<input type="text" class="form-control {%if unblacklisted_uuid is not none %}{%if unblacklisted_uuid==1 %}is-valid{% else %}is-invalid{%endif%}{%endif%}" id="unblacklist_uuid_input" placeholder="UUID Address">
									<div class="invalid-feedback">
										{%if unblacklisted_uuid==2 %}
											This UUID is not blacklisted
										{% else %}
											Incorrect UUID
										{% endif %}
									</div>
									<div class="valid-feedback">
										UUID Unblacklisted
									</div>
									<button type="button" class="btn btn-outline-secondary mt-2" onclick="window.location.href ='{{ url_for('unblacklist_uuid') }}?redirect=0&uuid='+$('#unblacklist_uuid_input').val();">Unblacklist UUID</button>
							</div>
						</div>
					</div>
					<div class="col-sm-5">
						<table class="table table-striped table-bordered table-hover" id="myTable_2">
							<thead class="thead-dark">
								<tr>
									<th style="max-width: 800px;">UUID</th>
									<th style="max-width: 800px;">Unblacklist UUID</th>
								</tr>
							</thead>
							<tbody>
								{% for uuid in list_blacklisted_uuid_2 %}
								<tr>
									<td>{{uuid}}</td>
									<td>
										<a href="{{ url_for('unblacklist_uuid') }}?page={{page}}&uuid={{uuid}}">
											<button type="button" class="btn btn-outline-danger">UnBlacklist UUID</button>
										</a>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
			  </div>
			</div>
		</div>

	</div>

	<div class="d-flex justify-content-center">
		<nav class="mt-4" aria-label="...">
			<ul class="pagination">
				<li class="page-item {%if page==1%}disabled{%endif%}">
					<a class="page-link" href="{{ url_for('blacklisted_uuid') }}?page={{page-1}}">Previous</a>
				</li>

				{%if page>3%}
					<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_uuid') }}?page=1">1</a></li>
					<li class="page-item disabled"><a class="page-link" aria-disabled="true" href="#">...</a></li>
					<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_uuid') }}?page={{page-1}}">{{page-1}}</a></li>
					<li class="page-item active"><a class="page-link" href="{{ url_for('blacklisted_uuid') }}?page={{page}}">{{page}}</a></li>
				{%else%}
				{%if page>2%}<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_uuid') }}?page={{page-2}}">{{page-2}}</a></li>{%endif%}
				{%if page>1%}<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_uuid') }}?page={{page-1}}">{{page-1}}</a></li>{%endif%}
				<li class="page-item active"><a class="page-link" href="{{ url_for('blacklisted_uuid') }}?page={{page}}">{{page}}</a></li>
				{%endif%}

				{%if nb_page_max-page>3%}
					<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_uuid') }}?page={{page+1}}">{{page+1}}</a></li>
					<li class="page-item disabled"><a class="page-link" aria-disabled="true" href="#">...</a></li>
					<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_uuid') }}?page={{nb_page_max}}">{{nb_page_max}}</a></li>
				{%else%}
					{%if nb_page_max-page>2%}<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_uuid') }}?page={{nb_page_max-2}}">{{nb_page_max-2}}</a></li>{%endif%}
					{%if nb_page_max-page>1%}<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_uuid') }}?page={{nb_page_max-1}}">{{nb_page_max-1}}</a></li>{%endif%}
					{%if nb_page_max-page>0%}<li class="page-item"><a class="page-link" href="{{ url_for('blacklisted_uuid') }}?page={{nb_page_max}}">{{nb_page_max}}</a></li>{%endif%}
				{%endif%}



				<li class="page-item {%if page==nb_page_max%}disabled{%endif%}">
					<a class="page-link" href="{{ url_for('blacklisted_uuid') }}?page={{page+1}}" aria-disabled="true">Next</a>
				</li>
			</ul>
		</nav>
		</div>

	{% include 'navfooter.html' %}
</body>

<script>
var table
$(document).ready(function(){

		table = $('#myTable_1').DataTable(
			{
				/*"aLengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
				"iDisplayLength": 10,*/
				"order": [[ 0, "asc" ]]
			}
		);

		table = $('#myTable_2').DataTable(
			{
				/*"aLengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
				"iDisplayLength": 10,*/
				"order": [[ 0, "asc" ]]
			}
		);

});
</script>

server/web/templates/edit_profile.html
<!DOCTYPE html>
<html>

<head>
  <title>D4-Project</title>
	<link rel="icon" href="{{ url_for('static', filename='img/d4-logo.png') }}">

  <!-- Core CSS -->
	<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='font-awesome/css/font-awesome.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/dataTables.bootstrap.min.css') }}" rel="stylesheet">

  <!-- JS -->
	<script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
	<script src="{{ url_for('static', filename='js/popper.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/jquery.dataTables.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/dataTables.bootstrap.min.js')}}"></script>

</head>
<body>

  {% include 'navbar.html' %}

	<div class="container-fluid">
		<div class="row">

			{% include 'sidebar_settings.html' %}

			<div class="col-12 col-lg-10" id="core_content">

				<div class="card mb-3 mt-1">
					<div class="card-header text-white bg-dark pb-1">
						<h5 class="card-title">My Profile :</h5>
					</div>
					<div class="card-body">

            <div class="row">
              <div class="col-xl-6">
                <div class="card text-center border-secondary">
                  <div class="card-body px-1 py-0">
                    <table class="table table-sm">
                      <tbody>
                        <tr>
                          <td>Email</td>
                          <td>{{user_metadata['email']}}</td>
                        </tr>
                        <tr>
                          <td>Role</td>
                          <td>{{user_metadata['role']}}</td>
                        </tr>
                        <tr>
                          <td>API Key</td>
                          <td>
                            {{user_metadata['api_key']}}
                            <a class="ml-3" href="{{url_for('settings.new_token')}}"><i class="fa fa-random"></i></a>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>

					</div>
				</div>

    	</div>
		</div>
	</div>

  {% include 'navfooter.html' %}

</body>

<script>
$(document).ready(function(){
  $("#nav-settings").addClass("active");
  $("#nav_edit_profile").addClass("active");
	$("#nav_my_profile").removeClass("text-muted");
} );

function toggle_sidebar(){
	if($('#nav_menu').is(':visible')){
		$('#nav_menu').hide();
		$('#side_menu').removeClass('border-right')
		$('#side_menu').removeClass('col-lg-2')
		$('#core_content').removeClass('col-lg-10')
	}else{
		$('#nav_menu').show();
		$('#side_menu').addClass('border-right')
		$('#side_menu').addClass('col-lg-2')
		$('#core_content').addClass('col-lg-10')
	}
}
</script>

</html>

server/web/templates/navbar.html
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('index') }}">
      <img src="{{ url_for('static', filename='img/d4-logo.png')}}" alt="D4 Project" style="width:80px;">
    </a>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link mr-3" id="nav-home" href="{{ url_for('index') }}">Home <span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item" mr-3>
          <a class="nav-link mr-3" id="nav-sensor" href="{{ url_for('sensors_status') }}">Sensors Status</a>
        </li>
        <li class="nav-item mr-3">
          <a class="nav-link" id="nav-server" href="{{ url_for('server_management') }}" tabindex="-1" aria-disabled="true">Server Management</a>
        </li>
        <li class="nav-item mr-3">
          <a class="nav-link" id="nav-settings" href="{{ url_for('settings.settings_page') }}" tabindex="-1" aria-disabled="true">Settings</a>
        </li>
        <li class="nav-item mr-3">
          <a class="nav-link" href="{{ url_for('logout') }}" tabindex="-1" aria-disabled="true"><i class="fa fa-sign-out"></i>Log Out</a>
        </li>
      </ul>
  </nav>

server/web/templates/navfooter.html
  <hr/ class="mb-0">
	<nav class="navbar bottom navbar-expand-sm navbar-light bg-light">
		<a class="navbar-brand" href="https://www.circl.lu/">
	    <img src="{{ url_for('static', filename='img/circl.png')}}" alt="circl" class="h-100" style="width: 180px;">
	  </a>
	  <img src="{{ url_for('static', filename='img/cef.png')}}" alt="cef" class="h-100" style="width: 500px;">
		<ul class="navbar-nav ml-auto">
	    <li class="nav-item">
				<a class="navbar-brand" href="https://www.d4-project.org/">
		      <img src="{{ url_for('static', filename='img/d4-logo.png')}}" alt="D4 Project" style="width:70px;">
		    </a>
	    </li>
	    <li class="nav-item">
				<a class="navbar-brand" href="https://github.com/D4-project/d4-core">
		      <i class="fa fa-github fa-3x mt-1"></i>
		    </a>
	    </li>
	  </ul>
	</nav>